
spring:
    application:
        name: eldoapplication
    jpa:
      generate-ddl: true
      hibernate:
        naming:
          strategy: ru.oz.mytutors.PhysicalNamingStrategyImpl
#    datasource:
#        driverClassName: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/eldo?characterEncoding=utf8&maxAllowedPacket=512000&rewriteBatchedStatements=true&verifyServerCertificate=false&useSSL=true
#        username: root
#        password: 123456
server:
    port: 9000
logging:
  level:
    org.springframework.transaction: DEBUG
    org.hibernate.tool.hbm2ddl.SchemaExport: DEBUG