spring:
    application:
        name: eldoapplication
    jpa:
      generate-ddl: true
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.99.100:3306/eldo?characterEncoding=utf8&maxAllowedPacket=512000&rewriteBatchedStatements=true&verifyServerCertificate=false&useSSL=true
        username: root
        password: 123456
server:
    port: 9000